### ISSUE TITLE
Can't return to link list in panel

### ISSUE THREAD

**Issue by willlma** [sajirdalas/alienPlanet#2]
Once I click on a link, it opens in the panel, replacing the list. There's no way to get back to the list.

**Comment by sajirdalas** [comment]
Refreshing should do it. But you are right, it is counter-intuitive as hell. The sure fire solution is to create my own interface for reddit comments instead of using reddit mobile and have a back button there. Until I get there a temporal back button injected into the reddit mobile HTML could do the trick... I think

**Comment by 53245342099** [comment]
Refreshing doesn't work for me.  I have to go to a new page in that tab and then go back for it to show the main panel again.  A back button would be good if you could do that.

**Comment by sajirdalas** [comment]
I have added a back button and some custom css to the panel on reddit mode
