### ISSUE TITLE
Not finding posts

### ISSUE THREAD

**Issue by 53245342099** [sajirdalas/alienPlanet#3]
Reddit Submission Finder finds eight instances of the following link being submitted to reddit, while alienPlanet finds none:

http://projects.propublica.org/graphics/workers-compensation-benefits-by-limb#

**Comment by sajirdalas** [comment]
Mmmm... it works fine on my side. Maybe there a network error I did not account for? What version of Firefox are you using?
![screenshot from 2015-03-25 10 27 30](https://cloud.githubusercontent.com/assets/3996162/6821696/a8efcb0e-d2d9-11e4-84d7-a174411960d5.png)

**Comment by sajirdalas** [comment]
I would like to use this open bug to self-report something search function that I saw yesterday and that is bugging me.

Videos such as this: https://www.youtube.com/watch?v=i-z14-ywH0Q only return one result in alienPlanet when I know for a fact it has been posted on another sub. I check and, indeed, the reddit search API is only returning one result because the post in the unlisted sub is using a redirect link, not the exact link that is in the browser bar.

However, both alienTube and Reddit Submission finder correctly detect the post with the redirect link and I have no clue how. I am going to look at their source today and try to figure out how they did it.

Thanks for reporting! Good progress is being made

**Comment by sajirdalas** [comment]
Thanks for reporting!

**Comment by 53245342099** [comment]
Bad at remembering version numbers. Current, up-to-date release channel.

**Comment by sajirdalas** [comment]
Thanks to some code borrowed from Reddit Submission Finder the search function has been greatly improved! It shows the correct results now
